### PR TITLE
Created SprintEntity, Repo and created table in changelog

### PR DESCRIPTION
**Pull request by sabaubogdan**

### CODE REVIEW

**Comment by sabaubogdan** [comment]
Hi, I will make additional changes and push&commit an updated version. 

Thank you,
Bogdan

**Comment by sabaudragos** [comment]
As far as the specs go, the code seems complete. What do you have in mind with an update?

**Review by sabaudragos — APPROVED** [review]

**Comment by sabaubogdan** [comment]
I started already to work on a related task, create Sprint Service(CRUD), modify also the UserStory & create the unit test.

Basically those two tasks will be on this branch.

Thank you,
Bogdan

**Comment by sabaudragos** [comment]
I disagree with this approach. The second task should go on a separate branch and a second PR should be opened. You can merge this branch anytime you want, I don't see any issues with it. This will enable you to create the second branch from master.

**Comment by sabaubogdan** [comment]
I will merge this one and create a new branch.

**Pull request merged**
